# -*- coding: utf-8 -*-
"""Function generate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G_kmnNQ8UsTSOYStryJ-lKkv00EL_3NH
"""

import pandas as pd

data_frame = pd.DataFrame(columns=['Name', 'Type'])
data_frame.head()

x=6
rows, cols = (x,x)
hash_arr = [['None' for i in range(cols)] for j in range(rows)]

hash_arr

def insert(data_frame, name, typ):
    if (name not in data_frame.Name.values) or (typ not in data_frame.Type.values):
        data_frame.loc[-1] = [name, typ]        
        data_frame.index = data_frame.index + 1  
        data_frame = data_frame.sort_index()
    return data_frame
                        
def search(data_frame, name):
    return data_frame.loc[data_frame['Name'] == name]
                        
def delete(data_frame, name):
    try:
        inx = data_frame.loc[data_frame['Name'] == name].index[0] 
        data_frame.drop([inx],axis=0,inplace=True)
        data_frame.reset_index(inplace=True)
        data_frame.drop('index',axis=1,inplace=True)
        return data_frame
    except:
        print('Name not found')
        return data_frame
        

def show():
    print(data_frame)

    
def update(data_frame, name=None, new_name=None, typ=None, new_typ=None):
    if name:
        if name in data_frame.Name.values:
            data_frame.loc[data_frame.Name == name,'Name'] = new_name
    if typ:
        if typ in data_frame.Type.values:
            data_frame.loc[data_frame.Type == typ,'Type'] = new_typ
            
    return data_frame



def getHashKey(data_frame, name):

      if (name in data_frame.Name.values):
          dx = data_frame.loc[data_frame['Name'] == name].index[0] 
          n_ascii= ord(name[0]) #ASCII value
          mod =n_ascii % x 
          n=data_frame.iloc[dx]['Name']
          t=data_frame.iloc[dx]['Type']
        
          for j in range(x):
              if (hash_arr[mod][j]=='None'):
                 hash_arr[mod][j]=[n,t]
                 break;

data_frame = insert(data_frame,'int','INTEGER')
data_frame = insert(data_frame,'function','FUNCTION')
data_frame = insert(data_frame,'i','ID')
data_frame = insert(data_frame,'5','NUM')
data_frame = insert(data_frame,'57','NUM')
data_frame = insert(data_frame,'float','Float')
data_frame = insert(data_frame,'53','NUM')

data_frame = insert(data_frame,'tin','INTEGER')

data_frame

search(data_frame, '5')

data_frame = delete(data_frame,'5')
data_frame

show()

data_frame= update(data_frame, '57','58')
data_frame

getHashKey(data_frame,'function')
hash_arr

getHashKey(data_frame,'float')
hash_arr

data_frame